### ISSUE TITLE
What board was this project based on?

### ISSUE THREAD

**Issue by x43x61x69** [progmem/Switch-Fightstick#3]
I noticed that this project use a `atmega32u4` MCU. Can you give me some info about the device this project was based as I seems to failed to have it run on a leonardo r3.

**Comment by progmem** [comment]
I sure can! I've successfully run this on two boards: Adafruit's 32u4 development board, and a previous project board that I've worked on (USBemani).

The Leonardo *does* share the same microcontroller, so that does make me a little curious as to what's going on. Are you using the Leonardo as a 'bare AVR' board, or with the Arduino IDE? If I can get some more information on how you're trying to get the code onto the Leonardo then I can see if I can help troubleshoot.

I don't have a Leonardo around, but I do have the....Arduino Micro? That one was also designed by Adafruit but is built with the Arduino IDE in mind, so maybe I can use that to help troubleshoot.

**Comment by x43x61x69** [comment]
Not sure why, but [this](https://github.com/WyseNynja/Splatoon-2-Drawing/) fork works on my Leonardo with MCU set to `atmega32u4`.

Tho seems the first line will always went off by 1 px for no reason.
