### ISSUE TITLE
What should I do if I want to press A ?

### ISSUE THREAD

**Issue by lanniu** [progmem/Switch-Fightstick#5]
Hello, What should I do if I want to press A?

**Comment by progmem** [comment]
Since there isn't as much clear insight/commenting in this code, let's go ahead and step through code. Generally speaking, communication over USB will happen something like this:

* The host (in this case, the Switch) will request a packet of data from the device
* The device will prepare and send a packet of data to the host, in the order of the USB descriptors.

The request portion is handled automatically by a constantly-running task:

**Comment by lanniu** [comment]
Is this function EVENT_USB_Device_ControlRequest()  send a packet of data to the host?
I replaced `GetNextReport(&JoystickInputData)` in EVENT_USB_Device_ControlRequest() with  
`memset(&JoystickInputData, 0, sizeof(USB_JoystickReport_Input_t));`
`JoystickInputData.Button = ButtonMap[2]; `
but it didn't work

**Comment by progmem** [comment]
Since there isn't as much clear insight/commenting in this code, let's go ahead and step through code. Generally speaking, communication over USB will happen something like this:

* The host (in this case, the Switch) will request a packet of data from the device
* The device will prepare and send a packet of data to the host, in the order of the USB descriptors.

The request portion is handled automatically by a constantly-running task:
```
// Process and deliver data from IN and OUT endpoints.
void HID_Task(void) {
```

This task will hit a function at some point, called [`GetNextReport`](https://github.com/progmem/Switch-Fightstick/blob/3916800cf42ae7d7a9d416c5ca5193f6e6aab288/Joystick.c#L237-L238), which is responsible for the preparation of data to send to the host:
```
// Prepare the next report for the host.
void GetNextReport(USB_JoystickReport_Input_t* const ReportData) {
```

Let's go ahead and look at this function a little further. In the function call, it's expecting a pointer to a `USB_JoystickReport_Input_t`; this is a `struct` that's built in the same order as the USB descriptors that the host knows of. In this `struct`, we have 16 buttons, a HAT, and two joysticks comprising of four axes total. You can see these definitions [here in Joystick.h](https://github.com/progmem/Switch-Fightstick/blob/3916800cf42ae7d7a9d416c5ca5193f6e6aab288/Joystick.h#L74-L83):
```
// Joystick HID report structure. We have an input and an output.
typedef struct {
	uint16_t Button; // 16 buttons; see JoystickButtons_t for bit mapping
	uint8_t  HAT;    // HAT switch; one nibble w/ unused nibble
	uint8_t  LX;     // Left  Stick X
	uint8_t  LY;     // Left  Stick Y
	uint8_t  RX;     // Right Stick X
	uint8_t  RY;     // Right Stick Y
	uint8_t  VendorSpec;
} USB_JoystickReport_Input_t;
```

So, let's say that any time we send a packet to the Switch, we simply want to hold A. To make things easier, we have an `enum` we can reference for button presses [here](https://github.com/progmem/Switch-Fightstick/blob/3916800cf42ae7d7a9d416c5ca5193f6e6aab288/Joystick.h#L57-L72):
```
typedef enum {
	SWITCH_Y       = 0x01,
	SWITCH_B       = 0x02,
	SWITCH_A       = 0x04,
	SWITCH_X       = 0x08,
	SWITCH_L       = 0x10,
	SWITCH_R       = 0x20,
	SWITCH_ZL      = 0x40,
	SWITCH_ZR      = 0x80,
	SWITCH_SELECT  = 0x100,
	SWITCH_START   = 0x200,
	SWITCH_LCLICK  = 0x400,
	SWITCH_RCLICK  = 0x800,
	SWITCH_HOME    = 0x1000,
	SWITCH_CAPTURE = 0x2000,
} JoystickButtons_t;
```

The A button would be `SWITCH_A`. If we want to make sure A is always held, we can do it during `GetNextReport` by doing the following. First, we need to make sure that our report is clean. We can do that by `memset`ing the report to  all zeroes:
```
memset(ReportData, 0, sizeof(USB_JoystickReport_Input_t));
```
Next, we need to make sure the sticks and the HAT refer to the centers, otherwise they'll be set to a direction (in games as an example, this would cause the camera and your character to move). During `GetNextReport` we can do the following to center the HAT and the two sticks:

```
ReportData->LX = 128;
ReportData->LY = 128;
ReportData->RX = 128;
ReportData->RY = 128;
ReportData->HAT = 0x08;
```

This will center the sticks (to 128/255), and set the HAT to the value of '8'. The HAT uses 0-7 to go from the top, all the way clockwise until we hit the top-left (you can see an example [here](https://github.com/progmem/Switch-Fightstick/blob/3916800cf42ae7d7a9d416c5ca5193f6e6aab288/Joystick.c#L269-L294) on the different HAT states).

Now, we want to make sure A is held. We can set the bit that represents A on the section of the `struct` used for buttons:
```
ReportData->Button |= SWITCH_A;
```

This uses an OR bitmath operator, which will make sure the bit represented by `SWITCH_A` is set, if it isn't already set. If you combine this with a conditional, you can check if a physical button on your device is pressed, and if it is, hold A while it is pressed (you would ideally want some debounce code as well, but that would be a separate discussion).

Also I actually posted this comment wayyyy too early further up the chain, so I deleted my original mis-post and moved it down here. Sorry about any confusion!

**Comment by progmem** [comment]
For clarity, here is what a `GetNextReport` function would look like that only holds the A button:

``` c
void GetNextReport(USB_JoystickReport_Input_t* const ReportData) {
	// Make sure ReportData is initialized to all zeroes!
	memset(ReportData, 0, sizeof(USB_JoystickReport_Input_t));
	// We'll center the axes and the HAT...
	ReportData->LX  = 128;
	ReportData->LY  = 128;
	ReportData->RX  = 128;
	ReportData->RY  = 128;
	ReportData->HAT = 0x08;
	// ...and hold our A button down!
	ReportData->Button |= SWITCH_A;
}
```

**Comment by lanniu** [comment]
Thank you for your help!

**Comment by progmem** [comment]
No problem! I'm going to go ahead and close this for now, since this doesn't really fall under the category of 'issue'.

Note that during `GetNextReport` you're allowed to do whatever you'd like, as long as it doesn't take *too* long. You can read physical button presses, play back buttons from an array, or even parse data that was read from some kind of Serial connection. If you take too long, a timeout will occur and the host may not necessarily see the data you want to send it. Depending on the host, this could result in it simply dropping the device.
