### ISSUE TITLE
sorry,but it still don't work on my switch

### ISSUE THREAD

**Issue by lanniu** [progmem/Switch-Fightstick#6]
sorry, but it still don't work on my switch  :( 
there is my code [http://www.lanniu.top/Joystick.c](url) ;)

**Comment by lanniu** [comment]
email: lanniu271067929@gmail.com

**Comment by progmem** [comment]
I do apologize, but the Issues section of this repository isn't meant for providing personalized technical support.

With that being said, I did double-check the code and verify that the A button is held; please note that I'm testing this on a standard PC in order to show this. Keep in mind that the Switch may not be expecting a button held on boot; plugging in a device with this code would be akin to plugging in a device with its A button constantly held. With that being said, check #7 for some more insight; this issue was with trying to tap a button, which was being tapped *too* fast for the Switch to recognize. In there is some code that's used as a timer-of-sorts, and you may be able to repurpose it to add in a delay, where the device won't hold A until after a certain amount of time has passed.
