### ISSUE TITLE
General Setup and Use

### ISSUE THREAD

**Issue by dongle-r** [progmem/Switch-Fightstick#9]
I know its been about a year since your last commit to this project, but I have stumbled upon this code while making researching making my own controller. I saw some of the other issues opened here about the type of board you use, but nothing about general setup and use of the code itself. I was hoping you could shed some light on the setup of a custom controller both through the hardware side and the setup for the switch?

**Comment by progmem** [comment]
Regarding the general setup, this project makes use of a library known as LUFA, which is a USB library for any of the Atmel AVR microcontrollers that have onboard USB. The ATMEGA32U4 is a common microcontroller used on a lot of AVR dev boards, such as the Arduino Leonardo and the Teensy2. The below is the 'in a nutshell' version.

Since this uses an AVR microcontroller, you need a way to compile AVR code. Atmel Studio aside, avr-gcc is the next means of building code for this project. Packages to install avr-gcc exist on **Windows** (I believe WinAVR is still updated?), **macOS** (what I use; avr-gcc is available as a Homebrew package), and **Linux**.

There's some AVR-specific C you're going to need to learn. If you're looking to make something simple (like, say, a Switch arcade stick), all you need to know is how to read a microcontroller pin for the most part. The pins on ports B and D (B0-B7, D0-D7 on most microcontroller devboards) are set to act as an input w/ pullup. If you want to change this, these pins are set this way in `SetupHardware`. You would ground one of these pins to simulate a button press.

If you're unfamiliar with reading an AVR microcontroller pin, the pins 0-7 map to bits, from lowest to highest. Reading pin B0 is as simple as testing the logical `PINB & 0x01`, and reading pin D7 is as simple as `PIND & 0x80`. Note that a button press is when a pin is **low**, so you'd test `(PINB & 0x01) == 0` to see if the button on pin B0 is grounded.

The function at the bottom, `GetNextReport`, prepares the `ReportData` object being sent to it by populating it with data. There's a `memset` that needs to be kept, but aside from that everything else can (and should) be changed out. Ideally, you'd test a pin to see if it's low, and if it is you'd set part of the report. You'll see some references like `ReportData->LX`, and these point to a portion of the USB report that can be set; the full definition is in **Joystick.h**.

There's also some helper values defined in **Joystick.h** that map to the Switch buttons by name, like `SWITCH_X` and `SWITCH_LCLICK`. So, you can write a statement like such to press to Home button when pin D4 is grounded:

```
if ((PIND & 0x10) == 0) {
  ReportData->Button |= SWITCH_HOME /* Sets the bit of SWITCH_HOME onto Button */
}
```

**Comment by dongle-r** [comment]
Thank you for the reply! I appreciate the write up, as it does clear up the major questions I have. A couple more things I don't understand. The file I want to build and push to the board is the Joystick.c correct (I know its not as simple as build and push, but is this on the right track)? Also is there any specific setup needed to connect the board/controller to the switch, or just plug it in and it'l be recognized by switch?

**Comment by progmem** [comment]
Regarding building, there's a `makefile` for that! You should be able to invoke `make` in order to build the code. `make clean` can be used to cleanup any files that were created as part of compilation.

For pushing to the board, check your specific devboard for more information. Many of them will accept a `.hex` file, which the build process will produce for you. Once programmed, the microcontroller is essentially an HID joystick, albeit one that looks like a HORI Pokken Tournament pad (and to the Switch, it treats it as a generic Pro Controller). Just plug it in and you're good to go!

**Comment by dongle-r** [comment]
Wonderful. Thank you again for all the help and for the repo!

**Comment by numberisnan** [comment]
Can I add this to the README? I've been looking all over for an explanation on how to use these libraries.
